<?php

namespace Database\Seeders;

use App\Models\AdminRole;
use App\Models\Permission;
use App\Models\Admin;
use Illuminate\Database\Seeder;

class AdminRbacSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            ['SUP', 'Support Admin', 'Customer support, complaints, and user governance support'],
            ['OPR', 'Operations Admin', 'Marketplace operations, properties, bookings, and governance operations'],
            ['FIN', 'Finance Admin', 'Wallets, payouts, refunds, and financial reporting'],
            ['REV', 'Reviewer Admin', 'Reviews, trust, badges, and dispute review'],
            ['SAF', 'Safety Admin', 'Safety cases, incidents, and safety governance'],
            ['ADM', 'Super Admin', 'Full administrative access'],
        ];
        foreach ($roles as [$code, $name, $description]) {
            AdminRole::updateOrCreate(
                ['code' => $code],
                ['name' => $name, 'description' => $description]
            );
        }

        $permissions = [
            ['profile.view', 'View admin profile', 'account'],
            ['profile.update', 'Update own admin profile', 'account'],
            ['users.view', 'View users', 'users'],
            ['users.update', 'Update users', 'users'],
            ['users.suspend', 'Suspend users', 'users'],
            ['users.ban', 'Ban users', 'users'],
            ['users.reactivate', 'Reactivate users', 'users'],
            ['users.delete', 'Delete users', 'users'],
            ['property.view', 'View properties', 'property'],
            ['property.create', 'Create properties', 'property'],
            ['property.update', 'Update properties', 'property'],
            ['property.delete', 'Delete properties', 'property'],
            ['property.approve', 'Approve properties', 'property'],
            ['property.reject', 'Reject properties', 'property'],
            ['property.suspend', 'Suspend properties', 'property'],
            ['property.ban', 'Ban properties', 'property'],
            ['badge.assign', 'Assign/revoke badges', 'trust'],
            ['booking.view', 'View bookings', 'booking'],
            ['booking.cancel', 'Cancel bookings', 'booking'],
            ['booking.force_complete', 'Force complete bookings', 'booking'],
            ['booking.extend', 'Extend bookings', 'booking'],
            ['payment.view', 'View payments', 'payment'],
            ['payment.refund', 'Process refunds', 'payment'],
            ['payout.view', 'View payouts', 'wallet'],
            ['payout.approve', 'Approve payouts', 'wallet'],
            ['payout.reject', 'Reject payouts', 'wallet'],
            ['complaint.view', 'View complaints', 'complaint'],
            ['complaint.update', 'Update complaints', 'complaint'],
            ['complaint.resolve', 'Resolve complaints', 'complaint'],
            ['complaint.escalate', 'Escalate complaints', 'complaint'],
            ['dispute.resolve', 'Resolve disputes', 'dispute'],
            ['dispute.appeal.reject', 'Reject dispute appeals', 'dispute'],
            ['rules.view', 'View configuration rules', 'governance'],
            ['rules.update', 'Update configuration rules', 'governance'],
            ['rules.commission.create', 'Create commission rules', 'governance'],
            ['rules.commission.update', 'Update commission rules', 'governance'],
            ['rules.commission.delete', 'Delete commission rules', 'governance'],
            ['rules.refund.create', 'Create refund rules', 'governance'],
            ['rules.refund.update', 'Update refund rules', 'governance'],
            ['rules.refund.delete', 'Delete refund rules', 'governance'],
            ['rules.cancellation.create', 'Create cancellation rules', 'governance'],
            ['rules.cancellation.update', 'Update cancellation rules', 'governance'],
            ['rules.cancellation.delete', 'Delete cancellation rules', 'governance'],
            ['report.view', 'View reports', 'report'],
            ['report.export', 'Export reports', 'report'],
            ['trust.view', 'View trust', 'trust'],
            ['trust.event.create', 'Create trust event', 'trust'],
            ['badge.view', 'View badges', 'trust'],
            ['badge.create', 'Create badges', 'trust'],
            ['badge.update', 'Update badges', 'trust'],
            ['badge.delete', 'Delete badges', 'trust'],
            ['badge.assign', 'Assign/revoke badges', 'trust'],
            ['safety.view', 'View safety cases', 'safety'],
            ['safety.acknowledge', 'Acknowledge SOS', 'safety'],
            ['safety.resolve', 'Resolve SOS', 'safety'],
            ['safety.false_alarm', 'Mark SOS false alarm', 'safety'],
            ['safety.incident.create', 'Create incidents', 'safety'],
            ['safety.incident.update', 'Update incidents', 'safety'],
            ['safety.incident.escalate', 'Escalate incidents', 'safety'],
            ['safety.report.view', 'View safety reports', 'safety'],
            ['wallet.view', 'View wallets', 'wallet'],
            ['wallet.status', 'Update wallet status', 'wallet'],
            ['wallet.adjust', 'Adjust wallet balance', 'wallet'],
            ['audit.view', 'View audit logs', 'audit'],
            ['activity.view', 'View admin activity', 'audit'],
            ['activity.suspicious', 'View suspicious activity', 'audit'],
            ['dashboard.view', 'View admin dashboard', 'dashboard'],
            ['admin.rbac.view', 'View admin roles and permissions', 'admin_rbac'],
            ['admin.rbac.manage', 'Manage admin roles and permissions', 'admin_rbac'],
        ];
        foreach ($permissions as [$key, $name, $module]) {
            Permission::updateOrCreate(
                ['key' => $key],
                ['name' => $name, 'module' => $module]
            );
        }

        $rolePermissions = [
            'SUP' => [
                    'activity.suspicious',
                    'activity.view',
                    'audit.view',
                    'booking.view',
                    'complaint.escalate',
                    'complaint.resolve',
                    'complaint.update',
                    'complaint.view',
                    'dashboard.view',
                    'admin.rbac.view',
                    'dispute.appeal.reject',
                    'dispute.resolve',
                    'profile.update',
                    'profile.view',
                    'property.view',
                    'users.update',
                    'users.view',
                ],
            'OPR' => [
                    'activity.suspicious',
                    'activity.view',
                    'audit.view',
                    'booking.cancel',
                    'booking.extend',
                    'booking.force_complete',
                    'booking.view',
                    'complaint.escalate',
                    'complaint.update',
                    'complaint.view',
                    'dashboard.view',
                    'admin.rbac.view',
                    'dispute.appeal.reject',
                    'dispute.resolve',
                    'profile.update',
                    'profile.view',
                    'property.approve',
                    'property.reject',
                    'property.suspend',
                    'property.update',
                    'property.view',
                    'report.view',
                    'rules.view',
                    'users.suspend',
                    'users.update',
                    'users.view',
                ],
            'FIN' => [
                    'activity.suspicious',
                    'activity.view',
                    'audit.view',
                    'dashboard.view',
                    'payment.refund',
                    'payment.view',
                    'payout.approve',
                    'payout.reject',
                    'payout.view',
                    'profile.update',
                    'profile.view',
                    'report.export',
                    'report.view',
                    'rules.cancellation.create',
                    'rules.cancellation.delete',
                    'rules.cancellation.update',
                    'rules.commission.create',
                    'rules.commission.delete',
                    'rules.commission.update',
                    'rules.refund.create',
                    'rules.refund.delete',
                    'rules.refund.update',
                    'rules.update',
                    'rules.view',
                    'users.view',
                    'wallet.adjust',
                    'wallet.status',
                    'wallet.view',
                ],
            'REV' => [
                    'activity.suspicious',
                    'activity.view',
                    'audit.view',
                    'badge.assign',
                    'badge.create',
                    'badge.delete',
                    'badge.update',
                    'badge.view',
                    'booking.view',
                    'complaint.view',
                    'dashboard.view',
                    'admin.rbac.view',
                    'dispute.appeal.reject',
                    'dispute.resolve',
                    'profile.update',
                    'profile.view',
                    'property.approve',
                    'property.view',
                    'report.view',
                    'trust.event.create',
                    'trust.view',
                ],
            'SAF' => [
                    'activity.suspicious',
                    'activity.view',
                    'audit.view',
                    'badge.assign',
                    'badge.view',
                    'booking.view',
                    'complaint.escalate',
                    'complaint.view',
                    'dashboard.view',
                    'dispute.resolve',
                    'profile.update',
                    'profile.view',
                    'property.suspend',
                    'property.view',
                    'report.view',
                    'safety.acknowledge',
                    'safety.false_alarm',
                    'safety.incident.create',
                    'safety.incident.escalate',
                    'safety.incident.update',
                    'safety.report.view',
                    'safety.resolve',
                    'safety.view',
                    'trust.view',
                    'users.ban',
                    'users.suspend',
                    'users.view',
                ],
            'ADM' => [
                    'activity.suspicious',
                    'activity.view',
                    'audit.view',
                    'badge.assign',
                    'badge.create',
                    'badge.delete',
                    'badge.update',
                    'badge.view',
                    'booking.cancel',
                    'booking.extend',
                    'booking.force_complete',
                    'booking.view',
                    'complaint.escalate',
                    'complaint.resolve',
                    'complaint.update',
                    'complaint.view',
                    'dashboard.view',
                    'admin.rbac.manage',
                    'admin.rbac.view',
                    'dispute.appeal.reject',
                    'dispute.resolve',
                    'payment.refund',
                    'payment.view',
                    'payout.approve',
                    'payout.reject',
                    'payout.view',
                    'profile.update',
                    'profile.view',
                    'property.approve',
                    'property.ban',
                    'property.create',
                    'property.delete',
                    'property.reject',
                    'property.suspend',
                    'property.update',
                    'property.view',
                    'report.export',
                    'report.view',
                    'rules.cancellation.create',
                    'rules.cancellation.delete',
                    'rules.cancellation.update',
                    'rules.commission.create',
                    'rules.commission.delete',
                    'rules.commission.update',
                    'rules.refund.create',
                    'rules.refund.delete',
                    'rules.refund.update',
                    'rules.update',
                    'rules.view',
                    'safety.acknowledge',
                    'safety.false_alarm',
                    'safety.incident.create',
                    'safety.incident.escalate',
                    'safety.incident.update',
                    'safety.report.view',
                    'safety.resolve',
                    'safety.view',
                    'trust.event.create',
                    'trust.view',
                    'users.ban',
                    'users.delete',
                    'users.reactivate',
                    'users.suspend',
                    'users.update',
                    'users.view',
                    'wallet.adjust',
                    'wallet.status',
                    'wallet.view',
                ],
        ];
        foreach ($rolePermissions as $code => $keys) {
            $role = AdminRole::where('code', $code)->firstOrFail();
            $ids = Permission::whereIn('key', $keys)->pluck('id')->all();
            $role->permissions()->sync($ids);
        }

        // Existing admin accounts retain full access initially.
        $superAdmin = AdminRole::where('code', 'ADM')->firstOrFail();
        Admin::where('role', 'admin')->orderBy('id')->chunkById(500, function ($admins) use ($superAdmin) {
            foreach ($admins as $admin) {
                $admin->adminRoles()->syncWithoutDetaching([$superAdmin->id]);
            }
        });
    }
}
